# yaml-language-server: $schema=schema/talkgroup_rules.yaml_schema.json
#
# Digital Voice Modem - Talkgroup Rules
#

# 
# Talkgroup Rules
#
groupVoice:
    # Textual name of the talkgroup.
  - name: Talkgroup 1
    # Secondary name/grouping of the talkgroup. (Informational)
    alias: Tactical
    #
    # Talkgroup Configuration
    #
    config:
      # Flag indicating whether this talkgroup is active or not.
      active: true
      # Flag indicating whether this talkgroup will only repeat with affiliations.
      affiliated: false
      # List of peer IDs included for this talkgroup (peers listed here will be selected for traffic).
      inclusion: []
      # List of peer IDs excluded for this talkgroup (peers listed here will be ignored for traffic).
      exclusion: []
      # List of peer talkgroup rewrites.
      rewrite: []
      # List of peer IDs that always receive traffic for this talkgroup regardless of affiliation rules.
      always: []
      # List of site CC peer IDs defining talkgroup access preference (peers listed here will be preferred for access,
      #   sites not listed here will be non-preferred and will cause a AFF_GRP_RSP DENY, typically triggering roaming).
      #   If this list is empty *all* peers are preferred. (Trunking Only)
      preferred: []
    #
    # Source Configuration
    #
    source:
      # Numerical talkgroup ID number.
      tgid: 1
      # DMR slot number.
      slot: 1

    # Textual name of the talkgroup.
  - name: Parrot
    # Secondary name/grouping of the talkgroup. (Informational)
    alias: Parrot/Testing
    #
    # Talkgroup Configuration
    #
    config:
      # Flag indicating whether this talkgroup is active or not.
      active: true
      # Flag indicating whether this talkgroup will only repeat with affiliations.
      affiliated: false
      # Flag indicating whether or not this talkgroup is a parrot talkgroup.
      parrot: true
      # List of peer IDs included for this talkgroup (peers listed here will be selected for traffic).
      inclusion: []
      # List of peer IDs excluded for this talkgroup (peers listed here will be ignored for traffic).
      exclusion: []
      # List of peer talkgroup rewrites.
      rewrite: []
      # List of peer IDs that always receive traffic for this talkgroup regardless of affiliation rules.
      always: []
      # List of site CC peer IDs defining talkgroup access preference (peers listed here will be preferred for access,
      #   sites not listed here will be non-preferred and will cause a AFF_GRP_RSP DENY, typically triggering roaming).
      #   If this list is empty *all* peers are preferred. (Trunking Only)
      preferred: []
    #
    # Source Configuration
    #
    source:
      # Numerical talkgroup ID number.
      tgid: 9990
      # DMR slot number.
      slot: 1

    # Textual name of the talkgroup.
  - name: Rewrite Example
    # Secondary name/grouping of the talkgroup. (Informational)
    alias: Example Group
    #
    # Talkgroup Configuration
    #
    config:
      # Flag indicating whether this talkgroup is active or not.
      active: true
      # Flag indicating whether this talkgroup will only repeat with affiliations.
      affiliated: false
      # Flag indicating whether or not this talkgroup is a parrot talkgroup.
      parrot: true
      # List of peer IDs included for this talkgroup (peers listed here will be selected for traffic).
      inclusion: []
      # List of peer IDs excluded for this talkgroup (peers listed here will be ignored for traffic).
      exclusion: []
      # List of peer talkgroup rewrites.
      rewrite:
          # Network Peer ID to rewrite this TGID for.
        - peerid: 9000990
          # Numerical talkgroup ID number.
          tgid: 9999
          # DMR slot number.
          slot: 1
      # List of peer IDs that always receive traffic for this talkgroup regardless of affiliation rules.
      always: []
      # List of site CC peer IDs defining talkgroup access preference (peers listed here will be preferred for access,
      #   sites not listed here will be non-preferred and will cause a AFF_GRP_RSP DENY, typically triggering roaming).
      #   If this list is empty *all* peers are preferred. (Trunking Only)
      preferred: []
    #
    # Source Configuration
    #
    source:
      # Numerical talkgroup ID number.
      tgid: 5
      # DMR slot number.
      slot: 1

    # Textual name of the talkgroup.
  - name: System Wide P25
    # Secondary name/grouping of the talkgroup. (Informational)
    alias: System Wide
    #
    # Talkgroup Configuration
    #
    config:
      # Flag indicating whether this talkgroup is active or not.
      active: true
      # Flag indicating whether this talkgroup will only repeat with affiliations.
      affiliated: false
      # List of peer IDs included for this talkgroup (peers listed here will be selected for traffic).
      inclusion: []
      # List of peer IDs excluded for this talkgroup (peers listed here will be ignored for traffic).
      exclusion: []
      # List of peer talkgroup rewrites.
      rewrite: []
      # List of peer IDs that always receive traffic for this talkgroup regardless of affiliation rules.
      always: []
      # List of site CC peer IDs defining talkgroup access preference (peers listed here will be preferred for access,
      #   sites not listed here will be non-preferred and will cause a AFF_GRP_RSP DENY, typically triggering roaming).
      #   If this list is empty *all* peers are preferred. (Trunking Only)
      preferred: []
    #
    # Source Configuration
    #
    source:
      # Numerical talkgroup ID number.
      tgid: 65535
      # DMR slot number.
      slot: 1

    # Textual name of the talkgroup.
  - name: System Wide DMR TS1
    # Secondary name/grouping of the talkgroup. (Informational)
    alias: System Wide
    #
    # Talkgroup Configuration
    #
    config:
      # Flag indicating whether this talkgroup is active or not.
      active: true
      # Flag indicating whether this talkgroup will only repeat with affiliations.
      affiliated: false
      # List of peer IDs included for this talkgroup (peers listed here will be selected for traffic).
      inclusion: []
      # List of peer IDs excluded for this talkgroup (peers listed here will be ignored for traffic).
      exclusion: []
      # List of peer talkgroup rewrites.
      rewrite: []
      # List of peer IDs that always receive traffic for this talkgroup regardless of affiliation rules.
      always: []
      # List of site CC peer IDs defining talkgroup access preference (peers listed here will be preferred for access,
      #   sites not listed here will be non-preferred and will cause a AFF_GRP_RSP DENY, typically triggering roaming).
      #   If this list is empty *all* peers are preferred. (Trunking Only)
      preferred: []
    #
    # Source Configuration
    #
    source:
      # Numerical talkgroup ID number.
      tgid: 16777215
      # DMR slot number.
      slot: 1

    # Textual name of the talkgroup.
  - name: System Wide DMR TS2
    # Secondary name/grouping of the talkgroup. (Informational)
    alias: System Wide
    #
    # Talkgroup Configuration
    #
    config:
      # Flag indicating whether this talkgroup is active or not.
      active: true
      # Flag indicating whether this talkgroup will only repeat with affiliations.
      affiliated: false
      # List of peer IDs included for this talkgroup (peers listed here will be selected for traffic).
      inclusion: []
      # List of peer IDs excluded for this talkgroup (peers listed here will be ignored for traffic).
      exclusion: []
      # List of peer talkgroup rewrites.
      rewrite: []
      # List of peer IDs that always receive traffic for this talkgroup regardless of affiliation rules.
      always: []
      # List of site CC peer IDs defining talkgroup access preference (peers listed here will be preferred for access,
      #   sites not listed here will be non-preferred and will cause a AFF_GRP_RSP DENY, typically triggering roaming).
      #   If this list is empty *all* peers are preferred. (Trunking Only)
      preferred: []
    #
    # Source Configuration
    #
    source:
      # Numerical talkgroup ID number.
      tgid: 16777215
      # DMR slot number.
      slot: 2
